### ISSUE TITLE
Can I arrange chess pieces according to an available position on the chessboard?

### ISSUE THREAD

**Issue by hungvu193** [huzongyao/JChineseChess#3]

**Comment by huzongyao** [comment]
now, have to change the source code , in 
https://github.com/huzongyao/JChineseChess/blob/master/app/src/main/java/com/hzy/chinese/jchess/activity/MainActivity.java

in line 131, 
String lastFen = mPreference.getString(GameConfig.PREF_LAST_FEN, "");
mGameLogic.restart(mComputerFlip, lastFen);

the string lastFen records the map of the game layout, change it and restart game, you will get different piece position

**Comment by hungvu193** [comment]
Thank you so much for your reply. After debug, I got a String like this :
`rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1`
I don't really understand the rules of this code. Can you please explain it? By the way,  How can I create a chessboard like this image?
![chess](https://user-images.githubusercontent.com/16502320/65443439-4ead9d80-de58-11e9-8dca-8dfc5a78c059.png)
